#Problem 

# Given: A string s of length at most 200 letters and four integers a, b, c and d.

#Return: The slice of this string from indices a through band c through d 
# (with space in between), inclusively. In other words, we should include elements s[b] and s[d]
# in our slice.

#Read in the .txt file generated by Rosalind
infile = open('rosalind_ini3.txt')

#Store the Rosalind generated string in given_string
given_string = infile.readline()

#Store the given indices in the slices variable
slices = infile.readline()
slices = slices.split(' ')

#Assign each index to a,b,c,d
a=int(slices[0])
b=int(slices[1])
c=int(slices[2])
d=int(slices[3])

#Index the given string to get the desired slices
a_to_b = given_string[a:b+1]
c_to_d = given_string[c:d+1]

#Print the two slices of the given string with a space in-between
print(f"{a_to_b} {c_to_d}")